/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppVeiculosRouteImport } from './routes/app/veiculos'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as App_layoutRouteImport } from './routes/app/__layout'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVeiculosRoute = AppVeiculosRouteImport.update({
  id: '/app/veiculos',
  path: '/app/veiculos',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/app/dashboard',
  path: '/app/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const App_layoutRoute = App_layoutRouteImport.update({
  id: '/app/__layout',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/app': typeof App_layoutRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/veiculos': typeof AppVeiculosRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/app': typeof App_layoutRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/veiculos': typeof AppVeiculosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/login': typeof LoginRoute
  '/app/__layout': typeof App_layoutRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/veiculos': typeof AppVeiculosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/app' | '/app/dashboard' | '/app/veiculos'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/app' | '/app/dashboard' | '/app/veiculos'
  id:
    | '__root__'
    | '/login'
    | '/app/__layout'
    | '/app/dashboard'
    | '/app/veiculos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LoginRoute: typeof LoginRoute
  App_layoutRoute: typeof App_layoutRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppVeiculosRoute: typeof AppVeiculosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/veiculos': {
      id: '/app/veiculos'
      path: '/app/veiculos'
      fullPath: '/app/veiculos'
      preLoaderRoute: typeof AppVeiculosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/app/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/__layout': {
      id: '/app/__layout'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof App_layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  LoginRoute: LoginRoute,
  App_layoutRoute: App_layoutRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppVeiculosRoute: AppVeiculosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
