/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthLayoutRouteImport } from './routes/_AuthLayout'
import { Route as AuthLayoutVeiculosRouteImport } from './routes/_AuthLayout.veiculos'
import { Route as AuthLayoutDashboardRouteImport } from './routes/_AuthLayout.dashboard'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_AuthLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutVeiculosRoute = AuthLayoutVeiculosRouteImport.update({
  id: '/veiculos',
  path: '/veiculos',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutDashboardRoute = AuthLayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthLayoutDashboardRoute
  '/veiculos': typeof AuthLayoutVeiculosRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthLayoutDashboardRoute
  '/veiculos': typeof AuthLayoutVeiculosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_AuthLayout': typeof AuthLayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_AuthLayout/dashboard': typeof AuthLayoutDashboardRoute
  '/_AuthLayout/veiculos': typeof AuthLayoutVeiculosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/dashboard' | '/veiculos'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/dashboard' | '/veiculos'
  id:
    | '__root__'
    | '/_AuthLayout'
    | '/login'
    | '/_AuthLayout/dashboard'
    | '/_AuthLayout/veiculos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_AuthLayout': {
      id: '/_AuthLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_AuthLayout/veiculos': {
      id: '/_AuthLayout/veiculos'
      path: '/veiculos'
      fullPath: '/veiculos'
      preLoaderRoute: typeof AuthLayoutVeiculosRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_AuthLayout/dashboard': {
      id: '/_AuthLayout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthLayoutDashboardRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
  }
}

interface AuthLayoutRouteChildren {
  AuthLayoutDashboardRoute: typeof AuthLayoutDashboardRoute
  AuthLayoutVeiculosRoute: typeof AuthLayoutVeiculosRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLayoutDashboardRoute: AuthLayoutDashboardRoute,
  AuthLayoutVeiculosRoute: AuthLayoutVeiculosRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
